export const TYPE_COLORS = {
  "full-time": "bg-green-500",
  "part-time": "bg-blue-500",
  internship: "bg-purple-500",
  freelance: "bg-orange-500",
  contract: "bg-gray-500",
} as const;

export const TECH_CATEGORIES = {
  frontend: {
    color: "bg-blue-500/20 text-blue-300 border-blue-500/30",
    techs: [
      "react",
      "vue",
      "angular",
      "svelte",
      "html",
      "css",
      "javascript",
      "typescript",
      "tailwindcss",
      "sass",
      "scss",
      "next.js",
      "nuxt.js",
      "gatsby",
    ] as string[],
  },
  backend: {
    color: "bg-green-500/20 text-green-300 border-green-500/30",
    techs: [
      "node.js",
      "express",
      "nest.js",
      "python",
      "django",
      "flask",
      "ruby",
      "rails",
      "php",
      "laravel",
      "java",
      "spring",
      "c#",
      ".net",
      "go",
      "rust",
    ] as string[],
  },
  database: {
    color: "bg-purple-500/20 text-purple-300 border-purple-500/30",
    techs: [
      "postgresql",
      "mysql",
      "mongodb",
      "redis",
      "sqlite",
      "dynamodb",
      "firebase",
      "supabase",
      "prisma",
    ] as string[],
  },
  devops: {
    color: "bg-orange-500/20 text-orange-300 border-orange-500/30",
    techs: [
      "aws",
      "azure",
      "gcp",
      "docker",
      "kubernetes",
      "terraform",
      "jenkins",
      "github actions",
      "gitlab ci",
      "vercel",
      "netlify",
      "heroku",
    ] as string[],
  },
  tools: {
    color: "bg-gray-500/20 text-gray-300 border-gray-500/30",
    techs: [
      "git",
      "github",
      "gitlab",
      "figma",
      "adobe",
      "postman",
      "insomnia",
      "webpack",
      "vite",
      "rollup",
    ] as string[],
  },
};
